# Generated by Django 4.2.3 on 2023-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "dishes"},
        ),
        migrations.AddField(
            model_name="dish",
            name="name_en",
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="name_uk",
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
    ]
