# Generated by Django 4.2.3 on 2023-07-24 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_dish_options_dish_name_en_dish_name_uk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="name_uk",
        ),
    ]
